# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_username = QtWidgets.QLabel(self.centralwidget)
        self.lb_username.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.lb_username.setObjectName("lb_username")
        self.lb_password = QtWidgets.QLabel(self.centralwidget)
        self.lb_password.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.lb_password.setObjectName("lb_password")
        self.lb_ftp_server_address = QtWidgets.QLabel(self.centralwidget)
        self.lb_ftp_server_address.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.lb_ftp_server_address.setObjectName("lb_ftp_server_address")
        self.le_ftp_server_address = QtWidgets.QLineEdit(self.centralwidget)
        self.le_ftp_server_address.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.le_ftp_server_address.setText("")
        self.le_ftp_server_address.setObjectName("le_ftp_server_address")
        self.le_username = QtWidgets.QLineEdit(self.centralwidget)
        self.le_username.setGeometry(QtCore.QRect(30, 80, 191, 20))
        self.le_username.setObjectName("le_username")
        self.le_password = QtWidgets.QLineEdit(self.centralwidget)
        self.le_password.setGeometry(QtCore.QRect(30, 130, 191, 20))
        self.le_password.setObjectName("le_password")
        self.td_server_response = QtWidgets.QTextBrowser(self.centralwidget)
        self.td_server_response.setGeometry(QtCore.QRect(280, 30, 461, 221))
        self.td_server_response.setObjectName("td_server_response")
        self.lb_server_response = QtWidgets.QLabel(self.centralwidget)
        self.lb_server_response.setGeometry(QtCore.QRect(280, 10, 101, 16))
        self.lb_server_response.setObjectName("lb_server_response")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(30, 180, 75, 23))
        self.btn_connect.setObjectName("btn_connect")
        self.btn_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_disconnect.setGeometry(QtCore.QRect(120, 180, 75, 23))
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.cb_show_password = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_show_password.setGeometry(QtCore.QRect(30, 150, 101, 17))
        self.cb_show_password.setObjectName("cb_show_password")
        self.comboBox_userAction = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_userAction.setGeometry(QtCore.QRect(30, 230, 111, 22))
        self.comboBox_userAction.setObjectName("comboBox_userAction")
        self.lb_action = QtWidgets.QLabel(self.centralwidget)
        self.lb_action.setGeometry(QtCore.QRect(30, 210, 47, 13))
        self.lb_action.setObjectName("lb_action")
        self.tree_local = QtWidgets.QTreeView(self.centralwidget)
        self.tree_local.setGeometry(QtCore.QRect(30, 300, 241, 192))
        self.tree_local.setObjectName("tree_local")
        self.btn_proceed = QtWidgets.QPushButton(self.centralwidget)
        self.btn_proceed.setGeometry(QtCore.QRect(150, 230, 75, 23))
        self.btn_proceed.setObjectName("btn_proceed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFTP_CLient = QtWidgets.QMenu(self.menubar)
        self.menuFTP_CLient.setObjectName("menuFTP_CLient")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menuFTP_CLient.addSeparator()
        self.menuFTP_CLient.addSeparator()
        self.menubar.addAction(self.menuFTP_CLient.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client by CAIO"))
        self.lb_username.setText(_translate("MainWindow", "User"))
        self.lb_password.setText(_translate("MainWindow", "Password"))
        self.lb_ftp_server_address.setText(_translate("MainWindow", "FTP Server Address"))
        self.lb_server_response.setText(_translate("MainWindow", "Server Response"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.btn_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.cb_show_password.setText(_translate("MainWindow", "Show Password"))
        self.lb_action.setText(_translate("MainWindow", "Action"))
        self.btn_proceed.setText(_translate("MainWindow", "Proceed"))
        self.menuFTP_CLient.setTitle(_translate("MainWindow", "Files"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

